"""
agent/state.py — LangGraph Agent State Definition
===================================================
Responsibility: Define the shared state (whiteboard) that all nodes
                read from and write to as the agent processes a question.

In LangChain (Projects 02-04): each chain had its own inputs/outputs.
In LangGraph (Project 05): ALL nodes share ONE state object.

State flows through the graph like this:
    User question
        → RouterNode reads state.question, writes state.tool_to_use
        → ToolNode reads state.tool_to_use, writes state.tool_result
        → LLMNode reads state.tool_result, writes state.final_answer
        → END returns state.final_answer to user

TypedDict is used so every field is clearly typed — no surprises.
Annotated + operator is used for fields that ACCUMULATE across nodes
(like messages) instead of overwriting each time.
"""

from typing import TypedDict, Annotated, List
import operator


class AgentState(TypedDict):
    """
    Shared state passed between all nodes in the LangGraph agent.

    Every node receives this state, does its job, and returns
    a dict with ONLY the fields it wants to update.
    LangGraph merges the update back into the full state automatically.

    Fields:
        question:     The original user question (never changes)
        tool_to_use:  Which tool the router decided to call
                      Options: "csv_tool", "sql_tool", "rag_tool", "llm_only"
        tool_result:  Raw result returned by the selected tool
        final_answer: Polished answer generated by the LLM node
        chat_history: List of past (question, answer) pairs for memory
                      Uses operator.add so new messages APPEND, not overwrite
        error:        Any error message if something goes wrong
    """

    # Original user question — set at start, never changed
    question: str

    # Router node writes this — tells tool node which tool to call
    # Values: "csv_tool" | "sql_tool" | "rag_tool" | "llm_only"
    tool_to_use: str

    # Tool node writes this — raw data retrieved by the tool
    tool_result: str

    # LLM node writes this — final polished answer shown to user
    final_answer: str

    # Conversation memory — Annotated + operator.add means
    # new messages are APPENDED, not overwritten
    # Without Annotated: state["chat_history"] = new_value (overwrites!)
    # With Annotated:    state["chat_history"] += new_value (appends!)
    chat_history: Annotated[List[str], operator.add]

    # Error handling — any node can write here if something fails
    error: str


# -------------------------------------------------------------------
# Helper function to create a fresh initial state
# Called at the start of every new conversation turn
# -------------------------------------------------------------------
def create_initial_state(question: str) -> AgentState:
    """
    Create a clean AgentState for a new question.

    Args:
        question: The user's question string

    Returns:
        AgentState with question set and all other fields empty/default
    """
    return AgentState(
        question=question,
        tool_to_use="",
        tool_result="",
        final_answer="",
        chat_history=[],
        error=""
    )


# -------------------------------------------------------------------
# Quick test — run directly to verify state structure
# Usage: python -m agent.state (from project root)
# -------------------------------------------------------------------
if __name__ == "__main__":
    # Create initial state
    state = create_initial_state("What is TechNova's total revenue?")
    print("Initial State:")
    for key, value in state.items():
        print(f"  {key}: {repr(value)}")

    # Simulate router node update
    state["tool_to_use"] = "rag_tool"
    print("\nAfter Router Node:")
    print(f"  tool_to_use: {state['tool_to_use']}")

    # Simulate tool node update
    state["tool_result"] = "TechNova revenue is Rs. 508 Crores"
    print("\nAfter Tool Node:")
    print(f"  tool_result: {state['tool_result']}")

    # Simulate memory update (append, not overwrite)
    state["chat_history"] += ["Q: What is revenue? A: Rs. 508 Crores"]
    state["chat_history"] += ["Q: What is profit? A: Rs. 76 Crores"]
    print("\nChat History (accumulated):")
    for msg in state["chat_history"]:
        print(f"  {msg}")